DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE if not exists requests (

    id                      bigint GENERATED BY DEFAULT AS IDENTITY,
    created_on              TIMESTAMP   NOT NULL,
    event_id                BIGINT      NOT NULL,
    requester_id            BIGINT      NOT NULL,
    status                  VARCHAR(15) NOT NULL,
    PRIMARY KEY (id)

);