services:
  ## CLOUD-SERVICES
  discovery-server:
    build: infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - ewm-net
    healthcheck:
      test: "curl --fail --silent discovery-server:8761/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 20s
      retries: 5

  config-server:
    build: infra/config-server
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=9091
      - SPRING_APPLICATION_NAME=config-server
    ports:
      - "9091:9091"
    healthcheck:
      test: "curl --fail --silent config-server:9091/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 30s
      retries: 5

  gateway-server:
    build: infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      event-service:
        condition: service_healthy
      comment-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      stats-server:
        condition: service_healthy
      request-service:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

      #USER
  user-db:
    image: postgres:16.1
    container_name: postgres-ewm-user-db
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-user
    volumes:
      - ./core/user-service/docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  user-service:
    build: core/user-service
    container_name: ewm-user-service
    depends_on:
      user-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/ewm-user
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8082
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:schema.sql
      - SPRING_SQL_INIT_CONTINUE_ON_ERROR=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=service-name
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9091
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    healthcheck:
      test: [ "CMD-SHELL", "pidof java || exit 1" ]
      timeout: 5s
      interval: 25s
      retries: 10

      ## STATS
  stats-server:
    build: stats/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_APPLICATION_NAME=stats-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9091
      - SERVER_PORT=9090
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:schema.sql
      - SPRING_SQL_INIT_CONTINUE_ON_ERROR=true
    healthcheck:
      test: "curl --fail --silent localhost:9090/actuator/health | grep UP || exit 1"
      timeout: 10s
      interval: 15s
      retries: 5
      start_period: 40s

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-stats
    networks:
      - ewm-net
    volumes:
      - ./stats/stats-server/docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

      # CORE-SERVICES
  event-service:
    build: core/event-service
    container_name: ewm-event-service
    depends_on:
      user-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
      event-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/ewm-event
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8083
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:schema.sql
      - SPRING_SQL_INIT_CONTINUE_ON_ERROR=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=event-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9091
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    healthcheck:
      test: [ "CMD-SHELL", "pidof java || exit 1" ]
      timeout: 5s
      interval: 25s
      retries: 10

  event-db:
    image: postgres:16.1
    container_name: postgres-ewm-event-db
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-event
    volumes:
      - ./core/event-service/docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  comment-db:
    image: postgres:16.1
    container_name: postgres-ewm-comment-db
    depends_on:
      config-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
      user-db:
        condition: service_healthy
      event-db:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-comment
    volumes:
      - ./core/comment-service/docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  comment-service:
    build: core/comment-service
    container_name: ewm-comment-service
    depends_on:
      comment-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
      event-service:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-db:5432/ewm-comment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8084
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:schema.sql
      - SPRING_SQL_INIT_CONTINUE_ON_ERROR=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=comment-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9091
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    healthcheck:
      test: [ "CMD-SHELL", "pidof java || exit 1" ]
      timeout: 5s
      interval: 25s
      retries: 10

  request-db:
    image: postgres:16.1
    container_name: postgres-ewm-request-db
    depends_on:
      user-db:
        condition: service_healthy
      event-db:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ewm-request
    volumes:
      - ./core/request-service/docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  request-service:
    build: core/request-service
    container_name: ewm-request-service
    depends_on:
      user-db:
        condition: service_healthy
      event-db:
        condition: service_healthy
      request-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
      event-service:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://request-db:5432/ewm-request
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8085
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:schema.sql
      - SPRING_SQL_INIT_CONTINUE_ON_ERROR=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=request-service
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9091
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    healthcheck:
      test: [ "CMD-SHELL", "pidof java || exit 1" ]
      timeout: 5s
      interval: 25s
      retries: 10

networks:
  ewm-net:
    driver: bridge