DROP TABLE IF EXISTS hits CASCADE;
CREATE TABLE IF NOT EXISTS hits
(
    hit_id    BIGINT GENERATED BY DEFAULT AS IDENTITY      NOT NULL,
    app VARCHAR(255)                                       NOT NULL,
    uri VARCHAR(255)                                       NOT NULL,
    ip VARCHAR(15)                                         NOT NULL,
    timestamp_hit TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_Hit_id PRIMARY KEY (hit_id)
);