DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE if not exists users
(
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(255) NOT NULL,
    user_name               VARCHAR(255) NOT NULL,
    is_admin                BOOLEAN DEFAULT FALSE
);
