spring:
  application:
    name: stats-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/ewm-stats
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
      circuitbreaker:
        enabled: true

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 10

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC