spring:
  application:
    name: main-service
  config:
    import: "configserver:http://config-server:9091"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      profile: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:discovery-server}:${eureka.instance.port:8761}/eureka/